// Odisha: district -> cities, towns, block HQs and well-known places (30 each).
// Small districts have few official towns, so lists include blocks and localities. Verify before official use.
const raw = {
  "Angul": "Angul,Talcher,Athamallik,Banarpal,Chhendipada,Kaniha,Kishorenagar,Pallahara,Nalconagar,Jarapada,Purunakote,Satkosia,Handidhua,Bantala,Rantalei,Deulbera,Kharagprasad,Dera,Tentulei,Bagedia,Kosala,Jagannathpur,Rengali,Gopalprasad,Thakurgarh,Sulia,Jindal Nagar,Bhalumunda,Talcher Coalfields,Anugul Town",
  "Balangir": "Balangir,Titlagarh,Patnagarh,Kantabanji,Agalpur,Bangomunda,Belpada,Deogaon,Gudvella,Khaprakhol,Loisingha,Muribahal,Puintala,Saintala,Turekela,Harishankar,Ranipur Jharial,Sindhekela,Kuturakhai,Salebhata,Larambha,Kendupali,Lathor,Chudapali,Bhurkamunda,Rajamunda,Tusura,Gandhamardan,Kapani,Sagadapali",
  "Balasore": "Balasore,Jaleswar,Soro,Nilgiri,Basta,Bahanaga,Bhogarai,Oupada,Remuna,Simulia,Chandipur,Panchalingeswar,Khaira,Baliapal,Raibania,Rasalpur,Bampada,Kuldiha,Bhimpur,Talasari,Berhampur Balasore,Markona,Singla,Gopalpur Balasore,Dhamra Road,Sartha,Jamkunda,Rupsa,Jagatpur,Bahabalpur",
  "Bargarh": "Bargarh,Barpali,Padampur,Attabira,Bhatli,Bheden,Bijepur,Gaisilet,Jharbandh,Paikmal,Sohela,Ambabhona,Rajborasambar,Barahaguda,Debrigarh,Ghens,Chichinda,Harbhanga,Dunguri,Bhukta,Lakhanpur,Jamla,Dumerpali,Kesaibahal,Sarandapali,Bhimkhoj,Kadobahal,Bhatli Town,Sambalpur Road,Paharsirgira",
  "Bhadrak": "Bhadrak,Basudevpur,Chandbali,Dhamnagar,Tihidi,Bonth,Bhandaripokhari,Dhusuri,Dhamra,Naikanidihi,Kharasuan,Barahapur,Garudabasa,Nuagaon,Sarapada,Gudiali,Rahania,Agarpada,Anantapur,Kanchana,Soro Road,Chandabali Port,Charampa,Baula,Kuruda,Pathuria,Betada,Dihapara,Bhadrak Town,Balipur",
  "Boudh": "Boudh,Kantamal,Harabhanga,Biranarasinghpur,Manamunda,Baghiapada,Kumbhirpada,Tikarpada,Chandrapur,Bhubanpur,Gandhipada,Patali,Khuntila,Baunsuni,Tarbha Road,Ambagaon,Nuapada,Kharikhai,Sarsara,Charichhak,Boinda,Bauda Town,Birmaharajpur Road,Kuturakhai,Kandhapada,Manamunda Town,Dasamantapur,Odapada,Mahanadi Ghat,Sitalpalli",
  "Cuttack": "Cuttack,Athagarh,Banki,Choudwar,Narasinghpur,Salipur,Baranga,Tangi,Tigiria,Niali,Mahanga,Nischintakoili,Kantapada,Dhabaleswar,Barang,Kakhadi,Jagatpur,Sidheswar,Gopalpur,Badamba,Raghunathpur,Cuttack Sadar,Bidanasi,Mangalabag,Buxi Bazar,Kathajodi,Chandinichowk,Naya Sarak,Machhua Bazar,Ranihat",
  "Deogarh": "Deogarh,Barkote,Reamal,Tileibani,Kuchinda,Pradhanpat,Rengali,Kundeigola,Tuman,Basantpur,Bamra Road,Jamankira,Chhatabar,Nuagaon,Kalabeda,Lakhna,Khandahata,Ghagarbeda,Sarapali,Kaintara,Parbatpur,Tumudibandha,Gopalpur,Bandhabahal,Gaisilet,Kankarbahal,Jhadeswar,Mahulpali,Jamunagarh,Debgarh Town",
  "Dhenkanal": "Dhenkanal,Bhuban,Kamakhyanagar,Hindol,Odapada,Parjang,Gondia,Kankadahad,Meramandali,Mahisapat,Balaramprasad,Bhapur,Bagadia,Saptasajya,Kapilash,Sarang,Hindol Road,Kuanrmunda,Rasol,Sadangi,Rajkishorenagar,Nuagaon,Tarava,Sogar,Jaleswarpur,Dhenkanal Town,Bhimkanda,Gandhia,Binjhagiri,Tilkana",
  "Gajapati": "Paralakhemundi,Mohana,Kashinagar,Gumma,Rayagada Block,Nuagada,R.Udayagiri,Adava,Tarava,Chandragiri,Bahuda,Mahendragiri,Rangeilunda,Sorada,Ankulpadar,Dharamgarh,Serango,Gosani,Tentulikhunti,Garabandha,Guma,Khajuripada,Ramagiri,Kerandi,Hatiapada,Boirani,Mahendratanaya,Pankalapadu,Banuguda,Kinchlingi",
  "Ganjam": "Berhampur,Aska,Bhanjanagar,Chhatrapur,Gopalpur,Hinjilicut,Kabisuryanagar,Purusottampur,Digapahandi,Khallikote,Chikiti,Sorada,Buguda,Polasara,Patrapur,Rangeilunda,Kodala,Beguniapada,Jagannath Prasad,Ganjam Town,Surada,Dharakote,Seragada,Kukudakhandi,Belaguntha,Golanthara,Gangapur,Gopalpur-on-Sea,Brahmapur,Ichhapuram Road",
  "Jagatsinghpur": "Jagatsinghpur,Paradip,Kujang,Erasama,Tirtol,Balikuda,Raghunathpur,Naugaon,Biridi,Sansarpur,Paradeep Garh,Mahakalpada,Bhogapur,Kendupatna,Jatni,Alanahat,Dasarathpur,Ersama Town,Kalikapur,Gadharisinghpur,Machhagaon,Nuagaon,Padmapur,Dhinkia,Rahama,Biju Patnaik Square,Tentulia,Fatehpur,Gobindpur,Kothi",
  "Jajpur": "Jajpur,Vyasanagar,Panikoili,Barchana,Bari,Binjharpur,Dasarathpur,Dharmasala,Korei,Rasulpur,Sukinda,Danagadi,Jenapur,Duburi,Kalinganagar,Jajpur Road,Baruan,Gobindapur,Chandikhol,Mangalpur,Kuakhia,Gopalpur,Dhanmandal,Tamka,Sarang,Sukinda Valley,Jaraka,Panchagaon,Jajpur Town,Barabati",
  "Jharsuguda": "Jharsuguda,Brajarajnagar,Belpahar,Lakhanpur,Kolabira,Kirmira,Laikera,Sripura,Rengali,Hirakud,Jhunjhuni,Lapanga,Ainthapali,Garposh,Katarbaga,Rampur,Kumarbandh,Samalaipadar,Telendihi,Jharsuguda Town,Banjari,Pandri Pani,Bhagipali,Kalimandir,Rajpur,Tungrei,Sarapali,Surdega,Haldia,Kendumundi",
  "Kalahandi": "Bhawanipatna,Kesinga,Junagarh,Dharmagarh,Narla,Lanjigarh,Jaipatna,Koksara,Madanpur Rampur,Thuamul Rampur,Golamunda,Kalampur,Kegaon,Karlamunda,Lanjigarh Road,Mohangiri,Utkela,Paharsiriguda,Nuapara,Jayapatna,Mukhiguda,Bhawanipatna Town,Chandrapur,Dharamgarh Town,Sagada,Rengali,Baner,Khariar Road,Bandhopada,Kesinga Town",
  "Kandhamal": "Phulbani,Baliguda,G.Udayagiri,Daringbadi,Tikabali,Phiringia,Raikia,Kotagarh,Khajuripada,Nuagaon,Chakapada,Tumudibandha,Sudrukumpa,Gochhapada,Brahmanigaon,Kalinga,Mandipanga,Barakhama,Pakari,Sarangada,Sarangagada,Phulnakhara,Lankagada,Mundigarh,Pabingia,Ranipathar,Belghar,Dasingbadi,Kandhamal Town,Bisipada",
  "Kendrapara": "Kendrapara,Pattamundai,Aul,Rajnagar,Rajkanika,Mahakalapada,Marshaghai,Derabish,Garadpur,Kanika,Bhitarkanika,Gupti,Gahirmatha,Jambu,Bagapatia,Dhamara,Ramnagar,Rajkanika Block,Mahakalpada Town,Kharinashi,Chandabali Road,Salipur Road,Harinagar,Mahanadi Bank,Gokulpur,Naugaon,Pentha,Nuagaon,Tentulia,Baliapal",
  "Kendujhar": "Kendujhar,Anandapur,Barbil,Joda,Champua,Telkoi,Jhumpura,Hatadihi,Ghasipura,Harichandanpur,Patna,Saharapada,Banspal,Ghatagaon,Nayakote,Bolani,Gonasika,Sanaghagara,Kiriburu,Meghahatuburu,Jajang,Kuanr,Tarapur,Kendujhargarh Town,Sadar,Soso,Kalimati,Sarapali,Basudevpur,Khandadhar",
  "Khordha": "Bhubaneswar,Khordha,Jatani,Balugaon,Banapur,Bolagarh,Begunia,Chilika,Tangi,Balianta,Balipatna,Chandaka,Khandagiri,Nandankanan,Rasulgarh,Patia,Pipili,Dhauli,Kalarahanga,Nirakarpur,Saheed Nagar,Unit 4,Jaydev Vihar,Old Town,Kharvel Nagar,Baramunda,Sundarpada,Infocity,Lingaraj Nagar,Mancheswar",
  "Koraput": "Koraput,Jeypore,Sunabeda,Semiliguda,Lamtaput,Kotpad,Boipariguda,Borigumma,Dasamantapur,Pottangi,Nandapur,Narayanpatna,Bandhugaon,Machhkund,Damanjodi,Laxmipur,Kundra,Similiguda,Dudhari,Padwa,Gupteswar,Sunki,Pitaguda,Jeypore Town,Rayagada Road,Lamataput,Kakirigumma,Narayanapatna,Kolab,Dumuriput",
  "Malkangiri": "Malkangiri,Kalimela,Mathili,Korukonda,Podia,Khairaput,Chitrakonda,Motu,Balimela,Jodamba,Mudulipada,Kudumulugumma,Papermetla,Govindapalli,Satiguda,Tamasa,Bejingiwada,Pandripani,Padmagiri,Mahupadar,Gumuka,Kuchinda,Chikapar,Kalimela Town,Malkangiri Town,Sunki,Bhairabi,Rasabeda,Sikapalli,Antaguda",
  "Mayurbhanj": "Baripada,Rairangpur,Karanjia,Udala,Betnoti,Bangriposi,Bisoi,Jamda,Khunta,Kuliana,Morada,Rasgovindapur,Samakhunta,Sukruli,Thakurmunda,Simlipal,Tiring,Raruan,Jashipur,Kaptipada,Sarat,Suliapada,Shamakhunta,Badampahar,Jamshola,Bahalda,Bhanjakia,Gopabandhunagar,Kusumi,Kendumundi",
  "Nabarangpur": "Nabarangpur,Umerkote,Jharigam,Kosagumuda,Papadahandi,Tentulikhunti,Nandahandi,Raighar,Chandahandi,Dabugam,Maidalpur,Bhatra,Podagada,Pujariguda,Bagabeda,Kundei,Jorigaon,Kodinga,Raighar Town,Kosagumuda Town,Tentuliguma,Gambharigaon,Chitrakonda,Lakhpur,Kotpad Border,Dhanmandal,Paparahandi,Boriguma,Narayanpatna,Jamunda",
  "Nayagarh": "Nayagarh,Khandapada,Odagaon,Ranpur,Dasapalla,Bhapur,Nuagaon,Itamati,Gania,Mahipur,Sarankul,Sunthi,Telkoi,Mahendratanaya,Sarasara,Remuna,Gadasila,Nuapada,Fategarh,Badagaon,Basudevpur,Kantilo,Madhyapur,Sankarpur,Gobindapur,Baghamari,Balipatna,Nayagarh Town,Pipili Road,Gundichapada",
  "Nuapada": "Nuapada,Khariar,Khariar Road,Komna,Boden,Sinapali,Kendupali,Jonk,Tarbod,Sunabeda,Dahuka,Patora,Chhuin,Khaprakhol,Rampur,Tikra,Chalna,Sargipali,Amera,Nuapada Town,Khaira,Bhaliapada,Mahulpali,Panchmahala,Bhaler,Bargaon,Nuakhai,Dumerpali,Gorla,Bijepur Road",
  "Puri": "Puri,Konark,Pipili,Satyabadi,Nimapara,Kakatpur,Gop,Astaranga,Delang,Brahmagiri,Kanas,Krushnaprasad,Chandrabhaga,Raghurajpur,Sakhigopal,Balighai,Chandanpur,Sipasarubali,Puri Town,Swargadwar,Baliapanda,Pentakota,Satapada,Balanga,Arakhakuda,Gundicha Temple Area,Samang,Ramachandi,Sarthak,Nuagaon",
  "Rayagada": "Rayagada,Gunupur,Gudari,Kashipur,Muniguda,Bissam Cuttack,Chandrapur,Kolnara,Padmapur,Ramanaguda,Kalyansinghpur,Therubali,Tikiri,Dongasil,Jaltar,Tikri,Mohana,Nuaguda,Rayagada Town,Chatikona,Bissamcuttack,Tikri Road,Kerpai,Harabhanga,Singhpur,Lankagada,Majhiguda,Tumba,Paiknuagaon,Jharnapada",
  "Sambalpur": "Sambalpur,Burla,Hirakud,Dhama,Jamankira,Maneswar,Naktideul,Rengali,Kuchinda,Jujumura,Dhankauda,Rairakhol,Remed,Sasan,Gaisilet,Ainthapali,Khetrajpur,Burla Town,Jamadarpali,Kasarpada,Katarbaga,Bareipali,Dhanupali,Modipada,Ainlatunga,Kadamdihi,Budharaja,Kuchinda Road,Ghunghutipali,Laida",
  "Subarnapur": "Sonepur,Binika,Birmaharajpur,Tarbha,Dunguripali,Ullunda,Binka,Rampur,Tarva,Biramaharajpur,Sonpur Ghat,Sadhubahal,Pashimkunda,Dhurelapada,Kharsal,Lathikata,Jharbandh,Subalaya,Mahanadi Bridge,Sirpur,Chhatrapada,Kerjangira,Basanta,Lalbagh,Manikpur,Bhagwanpur,Ghatikhal,Dhuliapali,Tentulikhunti,Kusumi",
  "Sundargarh": "Rourkela,Sundargarh,Rajgangpur,Biramitrapur,Bonai,Hemgir,Lephripara,Kutra,Lahunipara,Koida,Balisankara,Tangarpali,Subdega,Kuanrmunda,Banei,Panposh,Kansbahal,Ainthapali,Sector 19,Rourkela Steel City,Uditnagar,Koel Nagar,Chhend,Jalda,Bisra,Garposh,Gurundia,Nuagaon,Raiboga,Tensa"
};

const odishaLocations = Object.fromEntries(
  Object.entries(raw).map(([district, cities]) => [
    district,
    [...new Set(cities.split(",").map(c => c.trim()))].sort()
  ])
);

export default odishaLocations;
export const districts = Object.keys(odishaLocations);
